name: SimpleHub
version: 1.1
main: linareslinares\Hub
api:
- 5.0.0
author: "LinaresFunado [ YT: @linareslinares ]"
commands:
  hub:
    description: Regresa al Lobby
    permission: simple.hub
  sethub:
    description: Agrega el lobby al servidor
    permission: set.hub

permissions:
  simple.hub:
    default: true
  set.hub:
    default: op
